=== StephenFox1995/EnterpriseSystems/Lab4/invoice.xsd
<?xml version="1.0"?>
<!--
  Invoice Number, 
  Invoice Date, 
  Invoice Total, 
  Issued By, 
  Bill To, Item, 
  Payment Information
-->
<xs:schema 
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.dit.ie"
 xmlns="http://www.dit.ie"
 elementFormDefault="qualified">

  <xs:element name="invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="number" type="xs:integer"/>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="total" type="xs:decimal"/>

        <xs:element name="issuedby">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="address" type="xs:string"/>
              <xs:element name="bank">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="address" type="xs:string"/>
                    <xs:element name="telephone" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="items">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="id" type="xs:integer" minOccurs="1"/>
                    <xs:element name="quantity" type="xs:integer"/>
                    <xs:element name="price" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== StephenFox1995/EnterpriseSystems/Lab4/invoice.xml
<?xml version="1.0"?>

<invoice 
 xmlns="http://www.dit.ie"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.dit.ie invoice.xsd">
  <number>2390</number>
  <date>2010-01-10</date>
  <total>30.00</total>
  <issuedby>
    <name>Stephen Fox</name>
    <address>22 Ashington Park</address>
    <bank>
      <name>Permanent TSB</name>
      <address>2 Lower Grafton Street</address>
      <telephone>89089089</telephone>
    </bank>
  </issuedby>
  <items>
    <item>
      <name>Small Toy</name>
      <title>Play with this toy</title>
      <id>457894578954</id>
      <quantity>3</quantity>
      <price>43.9</price>
    </item>
    <item>
      <name>Small Toy</name>
      <title>Play with this toy</title>
      <id>457894578954</id>
      <quantity>3</quantity>
      <price>43.9</price>
    </item>
  </items>
</invoice>
